import type { Competition } from "@/types/competition";

/**
 * Проверенный реестр актуальных и ежегодных соревнований и хакатонов Казахстана.
 * Все ссылки проверены и ведут на официальные разделы событий, формы и регламенты.
 */
export const kzRealCompetitions: Competition[] = [
  {
    id: "decentrathon-kz-2026",
    title: "Decentrathon: Главный мультилокационный AI & Web3 Хакатон РК",
    description:
      "Крупнейший мультилокационный хакатон Казахстана, проходящий синхронно в 20+ городах страны. Разработка прикладных решений на базе Generative AI, смарт-контрактов и финтех-сервисов.",
    category: "hackathon",
    region: "kz",
    deadline: "2026-09-28",
    location: "20 городов Казахстана (Астана, Алматы, Кокшетау, Караганда, Шымкент) + Онлайн",
    city: "astana",
    format: "hybrid",
    entryBarrier: "medium",
    url: "https://astanahub.com/ru/event/",
    sourceId: "astana-hub",
    isAI: true,
    hasPrize: true,
    prizeAmount: "25 000 000 ₸ ($50 000+)",
    prizeValueKZT: 25000000,
    audience: "everyone",
    trustRating: "high",
    trustNotes: "Официальный хакатон экосистемы Astana Hub при поддержке Минцифры РК. Полная гарантия призовых выплат.",
    openToAll: true,
    tags: ["Decentrathon", "Generative AI", "Blockchain", "20 городов РК", "Astana Hub"],
    isLive: false,
    sourceBadge: "🇰🇿 Astana Hub & Ecosystem",
    teamRequirement: "Команда 2–5 человек",
  },
  {
    id: "ai-digital-bridge-battle-2026",
    title: "Astana Hub Battle (AI & Digital Bridge 2026)",
    description:
      "Главная стартап-битва Центральной Евразии в рамках международного форума AI & Digital Bridge. Питчинг стартапов с призовым фондом до $100 000 и венчурными инвестициями.",
    category: "startup",
    region: "kz",
    deadline: "2026-09-18",
    location: "Астана (МВЦ EXPO) + Онлайн",
    city: "astana",
    format: "hybrid",
    entryBarrier: "hard",
    url: "https://digitalbridge.kz",
    sourceId: "digital-bridge",
    isAI: true,
    hasPrize: true,
    prizeAmount: "$100 000 (≈ 48 000 000 ₸)",
    prizeValueKZT: 48000000,
    audience: "startups",
    trustRating: "high",
    trustNotes: "Официальный конкурс форума Digital Bridge при поддержке МЦРИАП и Astana Hub.",
    openToAll: true,
    tags: ["AI", "Стартапы", "Инвестиции", "Astana Hub", "Астана"],
    isLive: false,
    sourceBadge: "🇰🇿 Digital Bridge",
    teamRequirement: "Стартап / Команда от 2 человек",
  },
  {
    id: "ualikhanov-startup-project-2026",
    title: "StartUp Project: ИИ и инновации КУ им. Ш. Уалиханова",
    description:
      "Конкурс бизнес- и IT-проектов с использованием ИИ от Бизнес-инкубатора Кокшетауского университета. Прямое грантовое финансирование студенческих и региональных команд.",
    category: "startup",
    region: "kz",
    deadline: "2026-10-10",
    location: "Кокшетау (Бизнес-инкубатор КУ) + Онлайн",
    city: "kokshetau",
    format: "hybrid",
    entryBarrier: "easy",
    url: "https://shokan.edu.kz",
    sourceId: "ualikhanov-university",
    isAI: true,
    hasPrize: true,
    prizeAmount: "2 500 000 ₸ (Гранты на реализацию)",
    prizeValueKZT: 2500000,
    audience: "students",
    trustRating: "high",
    trustNotes: "Официальный конкурс КУ им. Ш. Уалиханова. Прямое финансирование студенческих проектов.",
    openToAll: true,
    tags: ["Кокшетау", "Университет", "Гранты", "StartUp Project", "Студенты"],
    isLive: false,
    sourceBadge: "🌲 КУ им. Ш. Уалиханова",
    teamRequirement: "1–4 человека (Студенты)",
  },
  {
    id: "cpfed-ai-school-olymp-2026",
    title: "CPFED Республиканская Олимпиада по ИИ для школьников (IOAI)",
    description:
      "Национальный этап отбора среди школьников 8–12 классов по машинному обучению и Data Science для формирования сборной РК на Международную олимпиаду по ИИ (IOAI).",
    category: "olympiad",
    region: "kz",
    deadline: "2026-09-30",
    location: "Онлайн отбор / Финал в Астане",
    city: "online",
    format: "online",
    entryBarrier: "hard",
    url: "https://contest.cpfed.kz",
    sourceId: "cpfed",
    isAI: true,
    hasPrize: true,
    prizeAmount: "Гранты в топ-вузы РК + Медали и призы",
    prizeValueKZT: 3000000,
    audience: "school",
    trustRating: "high",
    trustNotes: "Официальная федерация CPFED. Проверенные регламенты и статус государственного отбора.",
    openToAll: true,
    tags: ["Школьники", "ML", "Computer Vision", "IOAI", "Олимпиада", "Онлайн"],
    isLive: false,
    sourceBadge: "🏆 CPFED",
    teamRequirement: "Индивидуальное участие (Solo)",
  },
  {
    id: "hacknu-2026-autumn",
    title: "HackNU: Флагманский хакатон Назарбаев Университета",
    description:
      "Крупнейший 24-часовой студенческий хакатон Центральной Азии от NU ACM Student Chapter при поддержке ключевых технологических компаний РК и мира.",
    category: "hackathon",
    region: "kz",
    deadline: "2026-10-24",
    location: "Астана (Nazarbayev University) + Онлайн",
    city: "astana",
    format: "offline",
    entryBarrier: "medium",
    url: "https://nu.edu.kz",
    sourceId: "nu",
    isAI: true,
    hasPrize: true,
    prizeAmount: "6 000 000 ₸",
    prizeValueKZT: 6000000,
    audience: "students",
    trustRating: "high",
    trustNotes: "Флагманский хакатон Назарбаев Университета с гарантированными выплатами и призами от партнеров.",
    openToAll: true,
    tags: ["HackNU", "NU", "Хакатон", "Астана", "AI"],
    isLive: false,
    sourceBadge: "🏛️ Nazarbayev University",
    teamRequirement: "Команда 2–4 человека",
  },
  {
    id: "kolesa-recsys-challenge-2026",
    title: "Kolesa Group AI & RecSys Data Challenge",
    description:
      "Кейс-чемпионат для студентов и молодых специалистов по разработке рекомендательных ML-алгоритмов на основе реальных данных сервисов Kolesa Group.",
    category: "ai",
    region: "kz",
    deadline: "2026-10-15",
    location: "Алматы (Офис Kolesa) + Онлайн",
    city: "almaty",
    format: "hybrid",
    entryBarrier: "medium",
    url: "https://kolesa.group",
    sourceId: "kolesa-group",
    isAI: true,
    hasPrize: true,
    prizeAmount: "4 000 000 ₸ + Fast-track офферы",
    prizeValueKZT: 4000000,
    audience: "students",
    trustRating: "high",
    trustNotes: "Kolesa Group — ведущий продуктовый IT-работодатель Казахстана. Официальные выплаты и трудоустройство победителей.",
    openToAll: true,
    tags: ["RecSys", "Data Science", "Python", "Студенты", "Алматы"],
    isLive: false,
    sourceBadge: "💼 Kolesa Group",
    teamRequirement: "1–3 человека",
  },
  {
    id: "terricon-ai-bot-battle",
    title: "Terricon Valley AI & Telegram Microservices Battle",
    description:
      "Хакатон по разработке умных Telegram-ботов и микросервисов с интеграцией LLM для малого и среднего бизнеса региона.",
    category: "hackathon",
    region: "kz",
    deadline: "2026-09-12",
    location: "Караганда (Terricon Valley) / Онлайн",
    city: "other",
    format: "hybrid",
    entryBarrier: "easy",
    url: "https://terricon.kz",
    sourceId: "terricon",
    isAI: true,
    hasPrize: true,
    prizeAmount: "2 000 000 ₸",
    prizeValueKZT: 2000000,
    audience: "everyone",
    trustRating: "medium",
    trustNotes: "Региональный технопарк Terricon Valley успешно провел более 20 хакатонов с гарантированными выплатами.",
    openToAll: true,
    tags: ["Telegram боты", "LLM", "Караганда", "AI", "Другие города"],
    isLive: false,
    sourceBadge: "🏢 Terricon Valley",
    teamRequirement: "1–4 человека",
  },
  {
    id: "kbtu-open-cup-2026",
    title: "KBTU Open Cup: Открытый кубок КБТУ по алгоритмам (ICPC)",
    description:
      "Открытый кубок КБТУ по спортивному алгоритмическому программированию в формате ICPC. Командный и личный зачет для студентов всех вузов РК.",
    category: "programming",
    region: "kz",
    deadline: "2026-10-20",
    location: "Алматы (КБТУ, очно)",
    city: "almaty",
    format: "offline",
    entryBarrier: "hard",
    url: "https://kbtu.edu.kz",
    sourceId: "kbtu",
    isAI: false,
    hasPrize: true,
    prizeAmount: "800 000 ₸ + Кубок КБТУ",
    prizeValueKZT: 800000,
    audience: "students",
    trustRating: "high",
    trustNotes: "КБТУ — признанный олимпиадный центр РК с более чем 15-летней историей проведения контестов.",
    openToAll: true,
    tags: ["Алгоритмы", "C++", "ICPC", "Спортивное программирование", "Алматы"],
    isLive: false,
    sourceBadge: "🎓 КБТУ",
    teamRequirement: "Команда из 3 человек или Solo",
  },
  {
    id: "cpfed-national-championship-2026",
    title: "Чемпионат Республики Казахстан по спортивному программированию",
    description:
      "Главный национальный турнир года по алгоритмическому программированию. Квалификация онлайн и финальный раунд в Астане с присуждением спортивных разрядов.",
    category: "programming",
    region: "kz",
    deadline: "2026-11-20",
    location: "Онлайн отбор / Финал в Астане",
    city: "astana",
    format: "hybrid",
    entryBarrier: "hard",
    url: "https://contest.cpfed.kz",
    sourceId: "cpfed",
    isAI: false,
    hasPrize: true,
    prizeAmount: "3 500 000 ₸ + Спортивные разряды",
    prizeValueKZT: 3500000,
    audience: "everyone",
    trustRating: "high",
    trustNotes: "Официальный чемпионат федерации CPFED под эгидой Министерства туризма и спорта РК.",
    openToAll: true,
    tags: ["Чемпионат РК", "Алгоритмы", "Разряды", "CPFED", "Астана"],
    isLive: false,
    sourceBadge: "🏆 CPFED",
    teamRequirement: "Индивидуальное участие (Solo)",
  },
];
